### ISSUE TITLE
No hook to set Frame Size in sensor Interface

### ISSUE THREAD

**Issue by JemezKen** [CS460/SpaceRock#2]
I am working on the FPGA flag threads, and I noticed there is no way to set/adjust frame size for the sensor.  We can set the zoom size, which will set a frame size, but at this time, I can't feed a new frame size to the sensor.  I would guess we need to be able to pass an integer value (or values, if the frame size is not a square) to the sensor.

**Comment by scnaegle** [comment]
The Sensor doesn't care about the frame size except when calling getFrame
in which you pass the location and size of the frame. So the frame size
would just be stored in the FPGA code and not with the camera directly.

--Sean

**Comment by JemezKen** [comment]
OK.  If that is the case, we'll need to modify the FPGA diagram, as it shows the Control Registers sending a frame size to the sensor, separate from the zoom level, which also sets frame size indirectly, according to the code.  I'll admit, I missed that getFrame also could set frame size.  It does mean one less thread running, which is good.

Thanks.

________________________________
